version: '2'
services:

  database:
    container_name: tech-challenge-product-db
    build:
      context: database
      dockerfile: Dockerfile
    image: tech-challenge-product-db:latest
    ports:
      - "3306:3306"
    networks:
      - app_network
  application:
    container_name: tech-challenge-product-api
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-challenge-product-api:latest
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://tech_challenge_product_db:3306/tech_challenge_product
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  app_network:
    driver: bridge